manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: capnbard
      url-base: https://github.com/capnbard
  projects:
    - name: zmk-config
      remote: capnbard
      revision: master
      import: app/west.yml
  self:
    path: config
