manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: maximus5684
      url-base: https://github.com/maximus5684
  projects:
    - name: zmk
      remote: capnbard
      revision: master
      import: app/west.yml
  self:
    path: config
